apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-echo
  template:
    metadata:
      labels:
        app: hello-echo
    spec:
      containers:
      - name: hello-echo
        image: hashicorp/http-echo
        args: ["-text", "Hello, World!"]
        ports:
        - containerPort: 5678
